# Generated by Django 2.2.7 on 2019-11-20 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AS_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(default='', max_length=1000)),
                ('name_en', models.CharField(default='', max_length=1000)),
                ('year', models.IntegerField(verbose_name='Год создания')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в систему')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_leased', models.BooleanField(default=False, verbose_name='Сдана')),
                ('in_rent', models.BooleanField(default=False, verbose_name='Готова к аренде')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Машина', to='autoservice.Car')),
                ('rent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Арендующий', to='autoservice.AS_user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Владелец', to='autoservice.AS_user')),
            ],
        ),
        migrations.AddField(
            model_name='as_user',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Language'),
        ),
        migrations.AddField(
            model_name='as_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
