# Generated by Django 2.2.7 on 2019-11-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_auto_20191120_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='short_code',
            field=models.CharField(default='', max_length=3),
        ),
    ]
